apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "laravel.fullname" . }}-env
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.laravel.env }}
  {{ $key }}: "{{ $val | toString }}"
  {{- end}}